CREATE TABLE TR_PRODUCT (
PRODUCT_ID VARCHAR(16) NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(128) NOT NULL,
PRODUCT_SELLING_PRICE INTEGER NOT NULL,
PRODUCT_CATEGORY_ID INTEGER,
PRODUCT_STOCK INTEGER NOT NULL,
PRODUCT_COMMENT VARCHAR(2048),
PRODUCT_PHOTO_FILE_NAME1 VARCHAR(256),
PRODUCT_PHOTO_FILE_NAME2 VARCHAR(256),
PRODUCT_PHOTO_FILE_NAME3 VARCHAR(256),
PRODUCT_SHOW_FLAG INTEGER NOT NULL,
INSERT_DATE TIMESTAMP NOT NULL,
INSERT_USER VARCHAR(64) NOT NULL,
UPDATE_DATE TIMESTAMP NOT NULL,
UPDATE_USER VARCHAR(64) NOT NULL,
DELETE_DATE TIMESTAMP,
DELETE_USER VARCHAR(64)
);




ALTER TABLE TR_PRODUCT
ADD FOREIGN KEY (PRODUCT_CATEGORY_ID)
REFERENCES MS_PRODUCT_CATEGORY_INVENTORY (PRODUCT_CATEGORY_ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;